export const groupsData = [
  {
    id: "g1",
    grade: "الصف الثالث الثانوي",
    center: "غير محدد",
    groupName: "إحصاء",
    days: "السبت والثلاثاء",
    time: "11:30 صباحاً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-blue-500 to-primary-600",
    bgLight: "bg-blue-50 dark:bg-blue-900/10",
    borderLight: "border-blue-200 dark:border-blue-800"
  },
  {
    id: "g2",
    grade: "الصف الثاني الثانوي",
    center: "غير محدد",
    groupName: "بكالوريا",
    days: "السبت والثلاثاء",
    time: "1:00 ظهراً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-accent-500 to-accent-600",
    bgLight: "bg-orange-50 dark:bg-orange-900/10",
    borderLight: "border-orange-200 dark:border-orange-800"
  },
  {
    id: "g3",
    grade: "الصف الأول الثانوي",
    center: "سنتر الأباصيري",
    groupName: "المجموعة الأولى",
    days: "السبت والثلاثاء",
    time: "3:30 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-cyan-500 to-blue-600",
    bgLight: "bg-cyan-50 dark:bg-cyan-900/10",
    borderLight: "border-cyan-200 dark:border-cyan-800"
  },
  {
    id: "g4",
    grade: "الصف الأول الثانوي",
    center: "سنتر تزمنت الشرقية",
    groupName: "المجموعة الأولى",
    days: "الأحد والأربعاء",
    time: "3:30 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-green-500 to-emerald-600",
    bgLight: "bg-green-50 dark:bg-green-900/10",
    borderLight: "border-green-200 dark:border-green-800"
  },
  {
    id: "g5",
    grade: "الصف الأول الثانوي",
    center: "سنتر تزمنت الشرقية",
    groupName: "المجموعة الثانية",
    days: "الأحد والأربعاء",
    time: "5:00 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-teal-500 to-cyan-600",
    bgLight: "bg-teal-50 dark:bg-teal-900/10",
    borderLight: "border-teal-200 dark:border-teal-800"
  },
  {
    id: "g6",
    grade: "الصف الأول الثانوي",
    center: "سنتر تزمنت الشرقية",
    groupName: "المجموعة الثالثة",
    days: "الأحد والأربعاء",
    time: "6:15 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-indigo-500 to-violet-600",
    bgLight: "bg-indigo-50 dark:bg-indigo-900/10",
    borderLight: "border-indigo-200 dark:border-indigo-800"
  },
  {
    id: "g7",
    grade: "الصف الثاني الثانوي",
    center: "سنتر الأباصيري",
    groupName: "المجموعة الأولى",
    days: "السبت والثلاثاء",
    time: "2:30 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-purple-500 to-fuchsia-600",
    bgLight: "bg-purple-50 dark:bg-purple-900/10",
    borderLight: "border-purple-200 dark:border-purple-800"
  },
  {
    id: "g8",
    grade: "الصف الثاني الثانوي",
    center: "سنتر تزمنت الشرقية",
    groupName: "المجموعة الأولى",
    days: "الأحد والأربعاء",
    time: "5:00 مساءً",
    maxSeats: 50,
    bookedSeats: 0,
    isOpen: true,
    color: "from-pink-500 to-rose-600",
    bgLight: "bg-pink-50 dark:bg-pink-900/10",
    borderLight: "border-pink-200 dark:border-pink-800"
  }
];
